import type { Album, Listen } from './types'
import { PALETTES } from './art'

const P = Object.fromEntries(PALETTES.map((p) => [p.name, p.palette]))

const DAY = 86_400_000
const daysAgo = (n: number) => Date.now() - n * DAY
const dateAgo = (n: number) => new Date(Date.now() - n * DAY).toISOString().slice(0, 10)

export const SEED_ALBUMS: Album[] = [
  {
    id: 'kind-of-blue',
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    year: 1959,
    genre: 'Modal Jazz',
    label: 'Columbia',
    catalog: 'CL 1355',
    pressing: 'Mobile Fidelity UltraDisc One-Step 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog, original three-track master',
    condition: 'M / NM',
    rating: 5,
    notes: 'Side one runs a hair fast on the original — this cut fixes it. Box set, numbered 04412.',
    art: 'field',
    palette: P.Indigo,
    addedAt: daysAgo(612),
  },
  {
    id: 'dark-side-of-the-moon',
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    year: 1973,
    genre: 'Progressive Rock',
    label: 'Harvest',
    catalog: 'SHVL 804',
    pressing: 'Mobile Fidelity Original Master Recording',
    format: 'LP',
    speed: '33⅓ RPM',
    weight: '180 g',
    country: 'UK',
    master: 'All-analog, half-speed mastered',
    condition: 'NM / VG+',
    rating: 5,
    notes: 'Sleeve has a light ring wear shadow. Posters and stickers intact.',
    art: 'prism',
    palette: P.Graphite,
    addedAt: daysAgo(548),
  },
  {
    id: 'aja',
    title: 'Aja',
    artist: 'Steely Dan',
    year: 1977,
    genre: 'Jazz Rock',
    label: 'ABC Records',
    catalog: 'AB-1006',
    pressing: 'Analogue Productions UHQR 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '200 g',
    country: 'US',
    master: 'All-analog from the original master tape',
    condition: 'M / M',
    rating: 5,
    notes: 'Clarity on the horn stack is the reason to own this pressing.',
    art: 'arc',
    palette: P.Lacquer,
    addedAt: daysAgo(410),
  },
  {
    id: 'jazz-at-the-pawnshop',
    title: 'Jazz at the Pawnshop',
    artist: 'Arne Domnérus',
    year: 1977,
    genre: 'Live Jazz',
    label: 'Proprius',
    catalog: 'PROP 7778',
    pressing: 'Proprius 45 RPM reissue',
    format: '3×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'SE',
    master: 'All-analog, two-microphone live recording',
    condition: 'NM / NM',
    rating: 4,
    notes: 'The room noise is the point. Glasses, chairs, the whole pawnshop.',
    art: 'field',
    palette: P.Ochre,
    addedAt: daysAgo(366),
  },
  {
    id: 'cafe-blue',
    title: 'Café Blue',
    artist: 'Patricia Barber',
    year: 1994,
    genre: 'Vocal Jazz',
    label: 'Premonition',
    catalog: 'PREM-737-1',
    pressing: 'Mobile Fidelity UltraDisc One-Step 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog from the original master tape',
    condition: 'M / NM',
    rating: 5,
    notes: 'Track 4 is the system test. If the kick sounds soft, something upstream is wrong.',
    art: 'horizon',
    palette: P.Midnight,
    addedAt: daysAgo(300),
  },
  {
    id: 'brothers-in-arms',
    title: 'Brothers in Arms',
    artist: 'Dire Straits',
    year: 1985,
    genre: 'Rock',
    label: 'Vertigo',
    catalog: 'VERH 25',
    pressing: 'Mobile Fidelity UltraDisc One-Step 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'UK',
    master: 'Digital master, 1985 Sony PCM-1610',
    condition: 'NM / NM',
    rating: 4,
    notes: 'Digital at the source and still enormous. Full-length album, not the LP edit.',
    art: 'orb',
    palette: P.Steel,
    addedAt: daysAgo(268),
  },
  {
    id: 'saxophone-colossus',
    title: 'Saxophone Colossus',
    artist: 'Sonny Rollins',
    year: 1956,
    genre: 'Hard Bop',
    label: 'Prestige',
    catalog: 'PRLP 7079',
    pressing: 'Analogue Productions 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog, Van Gelder master',
    condition: 'NM / NM',
    rating: 5,
    notes: 'Mono. Tenor sits dead centre and about a metre behind the speakers.',
    art: 'split',
    palette: P.Amber,
    addedAt: daysAgo(214),
  },
  {
    id: 'folk-singer',
    title: 'Folk Singer',
    artist: 'Muddy Waters',
    year: 1964,
    genre: 'Chicago Blues',
    label: 'Chess',
    catalog: 'LP-1483',
    pressing: 'Analogue Productions 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog, original three-track master',
    condition: 'M / NM',
    rating: 5,
    notes: 'The acoustic guitar on "You Gonna Need My Help" is the best transient I own.',
    art: 'field',
    palette: P.Oxblood,
    addedAt: daysAgo(151),
  },
  {
    id: 'sunday-at-the-village-vanguard',
    title: 'Sunday at the Village Vanguard',
    artist: 'Bill Evans Trio',
    year: 1961,
    genre: 'Piano Jazz',
    label: 'Riverside',
    catalog: 'RLP 376',
    pressing: 'Analogue Productions 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog from the original master tape',
    condition: 'NM / NM',
    rating: 4,
    notes: 'LaFaro on the right channel, unusually forward. Live room is wide and low.',
    art: 'bands',
    palette: P.Olive,
    addedAt: daysAgo(88),
  },
  {
    id: 'getz-gilberto',
    title: 'Getz / Gilberto',
    artist: 'Stan Getz & João Gilberto',
    year: 1964,
    genre: 'Bossa Nova',
    label: 'Verve',
    catalog: 'V6-8545',
    pressing: 'Analogue Productions 45 RPM',
    format: '2×LP',
    speed: '45 RPM',
    weight: '180 g',
    country: 'US',
    master: 'All-analog from the original master tape',
    condition: 'NM / NM',
    rating: 4,
    notes: 'Stereo spread is extreme — guitar hard left, tenor hard right. Sit close.',
    art: 'field',
    palette: P.Marigold,
    addedAt: daysAgo(23),
  },
]

const SYSTEMS = {
  main: 'Technics SL-1200GR → Schiit Mani 2 → Yamaha A-S801 → Wharfedale Linton',
  study: 'Rega Planar 3 / Exact → Cambridge CXA61 → KEF LS50 Meta',
  vintage: 'Thorens TD 160 → Marantz 2270 → JBL L100 Classic',
  cans: 'Rega Planar 3 → Schiit Mani 2 → Bifrost → Sennheiser HD 650',
}

export const SEED_LISTENS: Listen[] = [
  {
    albumId: 'kind-of-blue',
    date: dateAgo(196),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'First play off the one-step. Cymbals decay far longer than the old CBS press.',
  },
  {
    albumId: 'kind-of-blue',
    date: dateAgo(94),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Sunday morning, side one only. Left the lights off.',
  },
  {
    albumId: 'kind-of-blue',
    date: dateAgo(31),
    location: 'Study',
    system: SYSTEMS.study,
    notes: 'LS50s cannot do the bass, but Bill Evans comes through beautifully.',
  },
  {
    albumId: 'kind-of-blue',
    date: dateAgo(6),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Warmed the amp for 30 minutes first. Worth it.',
  },
  {
    albumId: 'dark-side-of-the-moon',
    date: dateAgo(140),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Both sides, no interruptions. Clocks still resets the room.',
  },
  {
    albumId: 'dark-side-of-the-moon',
    date: dateAgo(45),
    location: 'Living room',
    system: SYSTEMS.vintage,
    notes: 'JBLs make this louder than it should be. Neighbours were out.',
  },
  {
    albumId: 'aja',
    date: dateAgo(120),
    location: 'Study',
    system: SYSTEMS.study,
    notes: 'Compared side one against the 1977 ABC press. UHQR wins on the ride cymbal.',
  },
  {
    albumId: 'aja',
    date: dateAgo(58),
    location: 'Study',
    system: SYSTEMS.cans,
    notes: 'Headphones. Peg pans further than I remembered.',
  },
  {
    albumId: 'aja',
    date: dateAgo(11),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Late. Only Deacon Blues, twice.',
  },
  {
    albumId: 'jazz-at-the-pawnshop',
    date: dateAgo(210),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Demo record for guests. The room sound sells it before the music does.',
  },
  {
    albumId: 'jazz-at-the-pawnshop',
    date: dateAgo(72),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Moved the speakers 10 cm further from the wall. Depth improved noticeably.',
  },
  {
    albumId: 'cafe-blue',
    date: dateAgo(160),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Cartridge alignment check. Sibilance on the vocal is clean now.',
  },
  {
    albumId: 'cafe-blue',
    date: dateAgo(83),
    location: 'Study',
    system: SYSTEMS.study,
    notes: 'Too much bass for this room. Track 4 overloads the corner.',
  },
  {
    albumId: 'cafe-blue',
    date: dateAgo(17),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Played it for J. He asked what the drummer was hitting.',
  },
  {
    albumId: 'brothers-in-arms',
    date: dateAgo(104),
    location: 'Kitchen',
    system: SYSTEMS.vintage,
    notes: 'Background listening while cooking. Not the way to hear it.',
  },
  {
    albumId: 'brothers-in-arms',
    date: dateAgo(29),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Why Worry at low volume, past midnight. Noise floor is dead silent.',
  },
  {
    albumId: 'saxophone-colossus',
    date: dateAgo(66),
    location: 'Study',
    system: SYSTEMS.cans,
    notes: 'Mono through headphones is oddly intimate. St. Thomas twice.',
  },
  {
    albumId: 'saxophone-colossus',
    date: dateAgo(9),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Blue 7 all the way through without touching my phone.',
  },
  {
    albumId: 'folk-singer',
    date: dateAgo(48),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Dead quiet pressing. Guitar body resonance is startling.',
  },
  {
    albumId: 'folk-singer',
    date: dateAgo(3),
    location: 'Living room',
    system: SYSTEMS.main,
    notes: 'Rainy afternoon. Side two, then again.',
  },
  {
    albumId: 'sunday-at-the-village-vanguard',
    date: dateAgo(35),
    location: 'Study',
    system: SYSTEMS.study,
    notes: 'Waltz for Debby is on the other volume — kept reaching for it.',
  },
].map((l) => ({
  ...l,
  id: `seed-${l.albumId}-${l.date}`,
  createdAt: new Date(l.date).getTime(),
}))
